name: fmcg_dbt

profile: fmcg_dbt

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  fmcg_dbt:
    +schema: raw

models:
  fmcg_dbt:
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: table
      +schema: silver
    marts:
      +materialized: table
      +schema: gold

