version: 2

models:

  - name: stg_products
    description: "Staging model for products with cleaned names, categories, and standardized divisions."
    columns:
      - name: product_code
        description: "SHA256 hash of the cleaned product name. Primary Key."
        tests:
          - unique
          - not_null

      - name: product_id
        description: "Original numeric ID or 999999 if invalid."
        tests:
          - not_null
          # Verify the regex cleaning logic worked (all IDs must be numbers)
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "^[0-9]+$"

      - name: division
        description: "Standardized product division based on category."
        tests:
          - not_null
          - accepted_values:
              values: 
                - 'Nutrition Bars'
                - 'Breakfast Foods'
                - 'Dairy & Recovery'
                - 'Healthy Snacks'
                - 'Hydration & Electrolytes'
                - 'Other'

      - name: category
        description: "Cleaned category name (Title Case, typo fixed)."
        tests:
          - not_null
      
      - name: variant
        description: "extracted weight/quantity from product name"
        tests:
          - not_null

  - name: stg_gross_price
    columns:
      - name: month
        tests:
          - not_null # Ensures COALESCE found a valid date format
      - name: gross_price
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0" # Ensures ABS() and cleanup worked
  - name: stg_customers
    columns:
      - name: customer_code
        tests:
          - unique
          - not_null
      - name: city
        tests:
          - not_null
          - accepted_values: 
              arguments: 
                values: ['Bengaluru', 'Hyderabad', 'New Delhi', 'Unknown']

